---
- name: Add security rule to Panorama
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "{{ rule_name }}"
    description: "{{ description }}"
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ destination_zone }}"
    source_ip: "{{ source_ip }}"
    destination_ip: "{{ destination_ip }}"
    application: "any"
    service: "{{ service }}"
    action: "{{ action }}"
    device_group: "{{ device_group }}"
    commit: false  # Commit separately later

- name: Commit candidate configuration
  paloaltonetworks.panos.panos_commit_panorama:
    provider: "{{ provider }}"
  register: results

- debug:
    msg: "Commit with job ID"

- name: Commit and Push template configuration
  paloaltonetworks.panos.panos_commit_push:
    provider: "{{ provider }}"
    style: "device group"
    name: "{{ device_group }}"
    include_template: no
  register: results

- debug:
    msg: "Push with job ID"
