- name: Add security rule to Panorama
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "{{ rule_name }}"
    description: "{{ description }}"
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ destination_zone }}"
    source_ip: "{{ source_ip }}"
    destination_ip: "{{ destination_ip }}"
    application: "any"
    service: "{{ service }}"
    action: "{{ action }}"
    device_group: "{{ device_group }}"
    commit: false  # Commit separately later

- name: Commit candidate configuration on Panorama
  paloaltonetworks.panos.panos_commit_panorama:
    provider: "{{ provider }}"
  register: panorama_commit_result

- debug:
    msg: "Commit with job ID {{ panorama_commit_result }}"

- name: Commit and push configuration to all device groups
  paloaltonetworks.panos.panos_commit_all:
    provider: "{{ provider }}"
    style: "device group"
    sync: true
  when: panorama_commit_result is succeeded
  register: commit_all_result

- debug:
    msg: "Commit and push completed with job ID {{ commit_all_result }}"
