---
- name: Add security rule to Panorama
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "{{ rule_name }}"
    description: "{{ description }}"
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ destination_zone }}"
    source_ip: "{{ source_ip }}"
    destination_ip: "{{ destination_ip }}"
    application: "any"
    service: "{{ service }}"
    action: "{{ action }}"
    device_group: "{{ device_group }}"
    commit: false  # Commit separately later

- name: "panorama: commit and push"
  block:
    - name: Commit candidate config to running config of Panorama
      paloaltonetworks.panos.panos_commit_panorama:
        provider: "{{ provider }}"
      run_once: true
 
    - name: Push
      paloaltonetworks.panos.panos_commit_push:
        provider: "{{ provider }}"
        style: 'device group'
        name: "ta01bdh6pocpa1"
      run_once: true
