---
- name: Add security rule to Panorama
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "{{ rule_name }}"
    description: "{{ description }}"
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ destination_zone }}"
    source_ip: "{{ source_ip }}"
    destination_ip: "{{ destination_ip }}"
    application: "any"
    service: "{{ service }}"
    action: "{{ action }}"
    device_group: "{{ device_group }}"
    commit: false  # Do not commit yet, commit will be done later in the playbook

- name: Commit the changes to Panorama
  paloaltonetworks.panos.panos_commit:
    provider: "{{ provider }}"
  register: panorama_commit_result  # Capture the commit result

- name: Push the commit to the firewall
  paloaltonetworks.panos.panos_commit_firewall:
    provider: "{{ provider }}"
    device_group: "{{ device_group }}"  # Specify the target device group
  when: panorama_commit_result is succeeded
