---
- name: Add security rule to Panorama
  paloaltonetworks.panos.panos_security_rule:
    provider: "{{ provider }}"
    rule_name: "{{ rule_name }}"
    description: "{{ description }}"
    source_zone: "{{ source_zone }}"
    destination_zone: "{{ destination_zone }}"
    source_ip: "{{ source_ip }}"
    destination_ip: "{{ destination_ip }}"
    application: "any"
    service: "{{ service }}"
    action: "{{ action }}"
    device_group: "{{ device_group }}"
    commit: false  # Commit separately later

- name: Commit the changes to Panorama
  paloaltonetworks.panos.panos_commit_panorama:
    provider: "{{ provider }}"
    sync: true  # Wait until commit completes
  register: panorama_commit_result

- name: Push changes to all firewalls in a device group
  paloaltonetworks.panos.panos_commit_push:
    provider: "{{ provider }}"
    sync: true
    include_template: true
    include_shared_objects: true
    device_group: "{{ device_group }}"  # Push to all firewalls in the group
    style: "device group"  # Required parameter to specify push type
  when: panorama_commit_result is succeeded
